from __future__ import annotations

import argparse
import sys
from collections import Counter

from common import ROOT, load_records

parser = argparse.ArgumentParser()
parser.add_argument("--check", action="store_true", help="fail if generated output is stale")
args = parser.parse_args()
records = sorted(load_records(), key=lambda item: (item["kind"], item["id"]))
counts = Counter(record["kind"] for record in records)
lines = ["# Generated research index", "", "Generated by `tools/generate_docs.py`; do not edit manually.", "", "## Counts", ""]
lines += [f"- {kind}: {counts[kind]}" for kind in sorted(counts)]
lines += ["", "## Symbols", "", "| ID | Kind | Confidence | Status | Summary |", "|---|---|---|---|---|"]
for record in records:
    summary = record["summary"].replace("|", "\\|").replace("\n", " ")
    lines.append(f"| `{record['id']}` | {record['kind']} | **{record['confidence'].upper()}** | {record['status']} | {summary} |")
content = "\n".join(lines) + "\n"
target = ROOT / "docs" / "generated" / "RESEARCH_INDEX.md"
if args.check:
    if not target.exists() or target.read_text(encoding="utf-8") != content:
        print(f"Generated documentation is stale: {target.relative_to(ROOT)}")
        sys.exit(1)
    print("Generated documentation is current.")
else:
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {target.relative_to(ROOT)}")
